build:
	docker build -t intro-to-python-notebook .
run:
	docker rm intro-to-python-nb
	docker run -p 8888:8888 --name intro-to-python-nb -v /Users/m.ramadiansyah/Documents/Labs/my-course/intro-to-python:/usr/src/app intro-to-python-notebook 